update husky

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,6 +1,24 @@
-echo "------- run here to check frontend lint ------- "
+#!/bin/sh
+. "$(dirname -- "$0")/_/husky.sh"
+
+echo "------- 🔍 Checking frontend lint and types -------"
 cd frontend
 npm run check:all
-echo "------- run here to check backend lint ------- "
+if [ $? -ne 0 ]; then
+  echo "❌ Errors found in frontend! Please fix the issues and re-commit."
+  echo "   git add ."
+  echo "   git commit again after fixing the issues."
+  exit 1
+fi
+
+echo "------- 🔍 Checking backend lint and types -------"
 cd ../backend
 npm run check:all
+if [ $? -ne 0 ]; then
+  echo "❌ Errors found in backend! Please fix the issues and re-commit."
+  echo "   git add ."
+  echo "   git commit again after fixing the issues."
+  exit 1
+fi
+
+echo "✅ All checks passed, you can proceed with the commit!"
